import Head from "next/head";
import { Container, Main } from "../components/sharedstyles";
import Header from "../components/header/header";
import Footer from "../components/footer/footer";

export default function Home() {
  return (
    <Container>
      <Head>
        <title>BNsystem</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Main></Main>
      <Footer></Footer>
    </Container>
  );
}
